#!/usr/bin/env bash
# installing and configuring haproxy

PATH_TO_CFG="/etc/haproxy/haproxy.cfg"
REMOTE_USER="ubuntu"
REMOTE_HOST="54.146.10.47"
ssh "$REMOTE_USER"@"$REMOTE_HOST" "sudo apt-get update -y && sudo apt install haproxy -y"

CONFIG_CONTENT="
frontend my_frontend
	bind *:80
	mode http
	timeout client 10s
	default_backend my_servers

backend my_servers
	mode http
	timeout connect 20s
	balance roundrobin
	server 335068-web-01 54.209.114.103:80
	server 335068-web-02 100.25.159.27:80
	timeout server 20s
"
echo "$CONFIG_CONTENT" | ssh "$REMOTE_USER"@"$REMOTE_HOST" "sudo tee $PATH_TO_CFG > /dev/null && sudo haproxy -c -f $PATH_TO_CFG && sudo systemctl restart haproxy"

