#!/usr/bin/env bash
# installing and configuring haproxy

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend my_frontend
	bind *:80
	mode http
	timeout client 10s
	default_backend my_servers

backend my_servers
	mode http
	timeout connect 20s
	balance roundrobin
	server 437370-web-01 54.209.114.103:80 check
	server 437370-web-02 100.25.159.27:80 check
	timeout server 20s
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
