#!/usr/bin/env bash
#script to print 1-100
#"Fizz" for multiples of 3
#"Buzz" for multiples of 5
#"FizzBuzz" for multiples of 3 and 5

for (( x=1; x < 101; x++ ))
do
   if (( x % 3 == 0 && x % 5 == 0));
   then
	echo "FizzBuzz"
   elif (( x % 3 == 0 ));
   then
	echo "Fizz"
   elif (( x % 5 == 0 ));
   then
	echo "Buzz"
   else
	echo "$x"
   fi
done
