#!/usr/bin/env bash
#script to display "Best School" 10 times,
#"bad luck" on the 4th time,
#"good luck" on the 8th

x=1
while [ "$x" -le 10 ]
do
   if [ "$x" -eq 4 ];
   then
	echo "bad luck"
   elif [ "$x" -eq 8 ];
   then
	echo "good luck"
   else
	echo "Best School"
   fi
   (( x++ ))
done
